update=4/2/2017 1:08:01 PM
version=1
last_client=kicad
[cvpcb]
version=1
NetIExt=net
[general]
version=1
[eeschema]
version=1
LibDir=../../Libraries/KiCAD Libraries/kicad-library/library
[eeschema/libraries]
LibName1=power
LibName2=device
LibName3=transistors
LibName4=conn
LibName5=linear
LibName6=regul
LibName7=74xx
LibName8=cmos4000
LibName9=adc-dac
LibName10=memory
LibName11=xilinx
LibName12=microcontrollers
LibName13=dsp
LibName14=microchip
LibName15=analog_switches
LibName16=motorola
LibName17=texas
LibName18=intel
LibName19=audio
LibName20=interface
LibName21=digital-audio
LibName22=philips
LibName23=display
LibName24=cypress
LibName25=siliconi
LibName26=opto
LibName27=atmel
LibName28=contrib
LibName29=valves
LibName30=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/74xgxx
LibName31=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/74xx
LibName32=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/ac-dc
LibName33=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/actel
LibName34=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/adc-dac
LibName35=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/allegro
LibName36=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/Altera
LibName37=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/analog_devices
LibName38=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/analog_switches
LibName39=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/atmel
LibName40=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/audio
LibName41=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/battery_management
LibName42=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/bbd
LibName43=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/bosch
LibName44=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/brooktre
LibName45=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/cmos_ieee
LibName46=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/cmos4000
LibName47=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/conn
LibName48=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/contrib
LibName49=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/cypress
LibName50=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/dc-dc
LibName51=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/device
LibName52=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/digital-audio
LibName53=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/diode
LibName54=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/display
LibName55=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/dsp
LibName56=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/elec-unifil
LibName57=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/ESD_Protection
LibName58=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/ftdi
LibName59=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/gennum
LibName60=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/graphic
LibName61=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/hc11
LibName62=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/intel
LibName63=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/interface
LibName64=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/intersil
LibName65=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/ir
LibName66=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/Lattice
LibName67=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/leds
LibName68=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/LEM
LibName69=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/linear
LibName70=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/logo
LibName71=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/maxim
LibName72=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/mechanical
LibName73=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/memory
LibName74=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/microchip
LibName75=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/microchip_dspic33dsc
LibName76=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/microchip_pic10mcu
LibName77=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/microchip_pic12mcu
LibName78=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/microchip_pic16mcu
LibName79=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/microchip_pic18mcu
LibName80=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/microchip_pic24mcu
LibName81=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/microchip_pic32mcu
LibName82=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/microcontrollers
LibName83=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/modules
LibName84=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/motor_drivers
LibName85=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/motorola
LibName86=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/motors
LibName87=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/msp430
LibName88=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/nordicsemi
LibName89=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/nxp
LibName90=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/nxp_armmcu
LibName91=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/onsemi
LibName92=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/opto
LibName93=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/Oscillators
LibName94=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/philips
LibName95=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/power
LibName96=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/Power_Management
LibName97=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/powerint
LibName98=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/pspice
LibName99=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/references
LibName100=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/regul
LibName101=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/relays
LibName102=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/rfcom
LibName103=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/RFSolutions
LibName104=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/sensors
LibName105=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/silabs
LibName106=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/siliconi
LibName107=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/stm8
LibName108=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/stm32
LibName109=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/supertex
LibName110=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/switches
LibName111=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/texas
LibName112=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/transf
LibName113=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/transistors
LibName114=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/triac_thyristor
LibName115=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/ttl_ieee
LibName116=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/valves
LibName117=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/video
LibName118=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/wiznet
LibName119=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/Worldsemi
LibName120=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/Xicor
LibName121=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/xilinx
LibName122=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/zetex
LibName123=C:/Users/William/Dropbox/Engineering/Libraries/KiCAD Libraries/kicad-library/library/Zilog
[pcbnew]
version=1
PageLayoutDescrFile=
LastNetListRead=RTC Dev Board-02.net
PadDrill=0.762
PadDrillOvalY=0.762
PadSizeH=1.524
PadSizeV=1.524
PcbTextSizeV=1.5
PcbTextSizeH=1.5
PcbTextThickness=0.3
ModuleTextSizeV=1
ModuleTextSizeH=1
ModuleTextSizeThickness=0.15
SolderMaskClearance=0
SolderMaskMinWidth=0
DrawSegmentWidth=0.2
BoardOutlineThickness=0.15
ModuleOutlineThickness=0.15
